---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.11 webserver wordpress.digicontrol.example chat.digicontrol.example
        - 172.16.0.12 graylog
        - 172.16.0.13 kibana kibana.4digicontrollabs.example
    
    - name: Criando diretorio /opt/filebeat
      synchronize:
        src: files/filebeat
        dest: /opt

    - name: Criando o arquivo syslog-tls.conf
      copy:
        src: files/server/syslog-tls.conf
        dest: /opt
        mode: 0644

    - name: Criando o arquivo bkp-banco.sh
      copy:
        src: files/bkp-banco.sh
        dest: /opt
        mode: 0644
